import '../models/place_model.dart';

class SampleData {
  static const List<PlaceModel> places = [
    PlaceModel(
      country: 'Indonesia',
      city: 'Bali',
      type: 'activity',
      name: 'Island Sightseeing Tour',
      category: 'Nature',
      cost: 80,
      durationHours: 4.5,
      rating: 4.8,
      interestTags: ['nature', 'beach', 'culture'],
    ),
    PlaceModel(
      country: 'Italy',
      city: 'Rome',
      type: 'activity',
      name: 'Old City Culture Walk',
      category: 'Culture',
      cost: 45,
      durationHours: 3,
      rating: 4.7,
      interestTags: ['culture', 'history', 'walking'],
    ),
    PlaceModel(
      country: 'Thailand',
      city: 'Phuket',
      type: 'activity',
      name: 'Sunset Snorkeling Trip',
      category: 'Beach',
      cost: 55,
      durationHours: 3,
      rating: 4.7,
      interestTags: ['beach', 'relax', 'adventure'],
    ),

    PlaceModel(
      country: 'Indonesia',
      city: 'Bali',
      type: 'hotel',
      name: 'Blue Coast Resort',
      category: '5-star hotel',
      cost: 220,
      durationHours: 24,
      rating: 4.9,
      interestTags: ['luxury', 'beach', 'relax'],
    ),
    PlaceModel(
      country: 'France',
      city: 'Paris',
      type: 'hotel',
      name: 'City Center Boutique Hotel',
      category: '4-star hotel',
      cost: 170,
      durationHours: 24,
      rating: 4.6,
      interestTags: ['city', 'shopping', 'culture'],
    ),
    PlaceModel(
      country: 'Japan',
      city: 'Tokyo',
      type: 'hotel',
      name: 'Tokyo Garden Stay',
      category: '3-star hotel',
      cost: 140,
      durationHours: 24,
      rating: 4.7,
      interestTags: ['city', 'culture', 'relax'],
    ),

    PlaceModel(
      country: 'Turkey',
      city: 'Istanbul',
      type: 'restaurant',
      name: 'Local Taste Restaurant',
      category: 'Local food',
      cost: 35,
      durationHours: 1.5,
      rating: 4.8,
      interestTags: ['food', 'culture', 'local'],
    ),
    PlaceModel(
      country: 'UAE',
      city: 'Dubai',
      type: 'restaurant',
      name: 'Skyline Fine Dining',
      category: 'Fine dining',
      cost: 95,
      durationHours: 2,
      rating: 4.7,
      interestTags: ['luxury', 'food', 'city'],
    ),
    PlaceModel(
      country: 'Italy',
      city: 'Rome',
      type: 'restaurant',
      name: 'Pasta House',
      category: 'Italian food',
      cost: 42,
      durationHours: 1.5,
      rating: 4.8,
      interestTags: ['food', 'culture', 'local'],
    ),
  ];
}